expname: SHAFT_megnet_binary_maxblock_6_grid
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS}/singlerun/${now:%Y-%m-%d}/${expname}_${now:%Y-%m-%d-%H-%M-%S}/

  sweep:
    dir: ${oc.env:HYDRA_JOBS}/multirun/${now:%Y-%m-%d-%H-%M-%S}/${expname}/
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread
      WANDB_DIR: ${oc.env:WABDB_DIR}

defaults:
  - train: default
  - SHAFT: train_SHAFT_Battery