chgflownet:
  _target_: pl_modules.CHGFlownet.CHGFlownet
  max_blocks: 6
  device: cuda:0
  lr: 0.0001
  lr_Z: 0.1
  scheduler_milestone: 5000
  gamma_scheduler: 1.0
  initlogZ: 0.0
  n_iterations: 1000000
  alpha_schedule: 1.0
  alpha: 1.0
  clampmin: -10.0
  clampmax: 10.0
  batch_size: 8
  save_freq: 100
  use_pretrain: false
  phidden_dim: 32
  pretrain_model_name: alignn
  proxy_model: M3GNet-MP-2018.6.1-Eform
  with_stop: true
  min_stop: 3
  policy_nn: graph_megnet_grid
  ele_set: battery
  max_ele: 3
  req_ele:
  - Li
  - Na
  - K
  max_atom: 200
  vpen_min: 0.1
  vpen_max: 0.1
  vpen_minmax: 0.01
  reward: reward_pref_bond_dict
  reward_beta: 1
  singlesg: false
  reward_min: 1.0e-05
  min_angle: 1.39626
  max_angle: 0.87267
  min_length: 4.0
  max_length: 11.0
  atom_mask_func: get_valid_mask_atom_type_one_group
  sg_list: sg_general